### ISSUE TITLE
Default toolchain not propagated to cygwin from msys

### ISSUE THREAD

**Issue by alexcrichton** [Diggsey/multirust-rs#12]
I installed multirust in MSYS2 but then when running in a cygwin shell it reports  that "no default toolchain is configured" (whereas in MSYS2 it works ok). Perhaps this is because `$HOME` is changing locations?

**Comment by Diggsey** [comment]
Yes, either define `MULTIRUST_HOME` to be somewhere consistent, or install multirust separately for cygwin.

This is because multirust-rs always installs for a single user (saves a lot of trouble with permissions, imagine if the overrides database was shared between users!) It's also how the python and ruby equivalents function.

Is there a reason why that is undesirable?

**Comment by alexcrichton** [comment]
I would personally want to install multirust once and call it a day, having it "just work" everywhere I try to use it. For example when I open up `cmd.exe` I also don't have my toolchains installed there. I *could* install all the toolchains in all the shells, but it'd be nice if they all shared data!

**Comment by Diggsey** [comment]
OK, I'll change it to only look at the `%USERPROFILE%` variables.

TBH, I find it extremely questionable that rust's `env::home_dir()` function looks for `%HOME%` first on windows: the way I see it, that should only be the case when you are specifically compiling for a unix-like environment, such as msys/cygwin, which each have their own target triples.

When compiling for a normal windows target, it shouldn't even look at `%HOME%`.

**Comment by Diggsey** [comment]
This should be fixed now.
