### ISSUE TITLE
MSVC can't install channels

### ISSUE THREAD

**Issue by alexcrichton** [Diggsey/multirust-rs#2]
I downloaded the 64-bit MSVC built of multirust and ran `multirust update` and was then met with:

```
error: binary packages are not yet provided for this host
```

**Comment by Diggsey** [comment]
Currently this happens if the most recent nightly build of `x86_64-pc-windows-msvc` rust failed, because it is then missing from the `channel-rustc-nightly` file.

This also happens with the original multirust/rustup combo. However, it should at least have a better error message, and should fall back to the most recent successful build for the given target.

**Comment by alexcrichton** [comment]
Ah ok I see what's going on. The builds actually all succeeded but perhaps seemed to be ordered incorrectly, I'll see if I can figure out what's going on from our end.

**Comment by alexcrichton** [comment]
We're  now gating on MSVC nightly builds, so this is probably a moot issue at this point. Plus it's working today!

**Comment by Diggsey** [comment]
\o/ I'd still like to improve it slightly, so I've opened a new issue here: #10
