### ISSUE TITLE
Use docopt for multirust binary

### ISSUE THREAD

**Issue by jwilm** [Diggsey/multirust-rs#38]
Hey @Diggsey,

I've been poking around this project a bit to figure out the library API, and I had a look at the cli file. It's sort of..... unapproachable :grin:. The API multirust exposes could easily be written using [docopt](https://github.com/docopt/docopt.rs), and it would make maintenance a lot easier.

Are you open to a PR for this if it showed up?

**Comment by Diggsey** [comment]
Hi @jwilm, I'm a little skeptical of tools which generate the CLI from the usage text, as I usually find it too restrictive. I'm not prepared to switch to docopt purely on the basis of maintenance, as I personally find cli.rs to be quite structured and easy to modify. It is long, but that's mainly due to the amount of descriptive text about each command.

However, I *may* be open to switching if the alternative provides other tangible benefits (such as being able to handle OsStrings correctly) without having signficant drawbacks.

**Comment by azerupi** [comment]
[Clap-rs](https://github.com/kbknapp/clap-rs) is another contender that is worth looking into.

**Comment by Diggsey** [comment]
@azerupi clap-rs is what multirust currently uses.

**Comment by azerupi** [comment]
Ah sorry, my mistake. I should have looked before saying anything. 
When @jwilm said "unapproachable" I assumed something else was used because I find Clap-rs one of the best structured and easy ways to create a CLI. :)

After taking a look at `cli.rs` I don't find it "unapproachable". If you have used clap-rs a little it is not hard to understand.  It is true that the "help" strings are very long, maybe moving them into constants above or below would make the CLI code more clear?

**Comment by jwilm** [comment]
Hey @Diggsey and @azerupi,

Thanks for the discussion about this. You're right that docopt would be too restrictive for multirust-rs; it doesn't appear to support extended help for subcommands. I'm on a bit of a docopt kick lately since it has [made my CLI source files][racerd-usage] stupid simple. I should have looked more closely at what the multirust-rs cli.rs was actually doing first. Sorry about that! At least there's an issue in the history now for the next person who might be curious about cli.rs/docopt :smile:.

@azerupi you're totally right that the clap-rs API is straight-forward. I would argue that having no API is simpler, though. It will definitely be my go-to arg parser if/when I run into the limits of docopt.

clap-rs seems to be a good choice here; closing.

[racerd-usage]: https://github.com/jwilm/racerd/blob/master/src/bin/racerd.rs#L14-L41
