### ISSUE TITLE
Running multirust installer hangs on Windows 

### ISSUE THREAD

**Issue by alexcrichton** [Diggsey/multirust-rs#6]
For example:

```
$ multirust
This is the currently installed multirust binary.
```

(and it never returns to the shell). If I hit "enter" it'll return, but perhaps shouldn't require that? I also ran into this when installing or maybe updating a toolchain, but I forget the precise situation.

**Comment by Diggsey** [comment]
This is intentional: when run with no arguments it will wait for input before exiting in case it wasn't run from a terminal. The alternative results in momentarily flashing up a terminal which disappears before you can read the message, if the program is run directly.

It should never happen when installing or updating a toolchain.

**Comment by alexcrichton** [comment]
Ah ok, I find this surprising but if it's intentional I'll close.

**Comment by alexcrichton** [comment]
Ah ok so I just ran the installer and after it printed "info: Installed" it ended up hanging waiting for more data, so that's at least a reproduction!

**Comment by Diggsey** [comment]
Oh, I phrased that ambiguously. It should be read as "It should never happen when (installing or updating) a toolchain". ie, It *will* happen when installing multirust itself, as that's precisely the case where it needs to stick around in case it's been run directly from the browser or filesystem, and so the terminal would otherwise disappear.

If you can think of a better way to handle this, I'll keep the issue open as a feature request.

**Comment by alexcrichton** [comment]
Oh... interesting... I would expect 99% of users to work with multirust from a CLI, not from a GUI (e.g. it's a power user tool)

**Comment by Diggsey** [comment]
Right, but typically you would download multirust using one of the binary links in the readme, and it would be very confusing if after downloading and running the installer, you answered the two questions and then the terminal just disappeared, with no indication that it had been installed.
