### ISSUE TITLE
Running "multirust" spawns thousands of processes

### ISSUE THREAD

**Issue by alexcrichton** [Diggsey/multirust-rs#9]
I ran "multirust" (no arguments) on Windows and now I've got thousands of processes running, presumably waiting for input.

(perhaps this would be a good time to add tests to the repo?)

**Comment by Diggsey** [comment]
Yes, tests are desperately needed, I know :stuck_out_tongue: 

To be fair, I can't actually use `cargo test` on windows at the moment until I can pass custom dynamic libraries to openssl, because of the issue with static linking on windows we were discussing on IRC.

**Comment by Diggsey** [comment]
OK, this should be fixed now, just make sure that the *first* thing you do is run "multirust install" with the new version.

I thought it would be a good idea to test whether multirust is working empirically: by running `rustc --multirust` and checking that the argument is intercepted (if it's not, rustc will exit with a non-zero code due to an invalid argument). Unfortunately during the CLI refactoring, this check got enabled for `multirust proxy` itself...

Tests are on the way!

**Comment by Diggsey** [comment]
OK, this should be fixed now, just make sure that the *first* thing you do is run "multirust install" with the new version.

I thought it would be a good idea to test whether multirust is working empirically: by running `rustc --multirust` and checking that the argument is intercepted (if it's not, rustc will exit with a non-zero code due to an invalid argument). Unfortunately during the CLI refactoring, this check got enabled for `multirust proxy` itself...

Tests are on the way!

**Comment by Diggsey** [comment]
I've added some shell/batch scripts to test the CLI. They're very minimal but they should at least catch things like this.
